PROJECT/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task/',include("task.urls"))
]

task/urls.py
from django.urls import path
from . import views

app_name = "task"
urlpatterns = [
    path("", views.index,name="index"),
    path("add/", views.add,name="add"),
    path("complete/<int:task_id>/", views.complete_task, name="complete_task"),
    path("delete/<int:task_id>/", views.delete_task, name="delete_task"),
    path("edit/<int:task_id>/", views.edit_task, name="edit_task"),
]

task/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=255)
    completed = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.task

task/views.py
from django.shortcuts import render, get_object_or_404
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Task

class NewTaskForm(forms.ModelForm):
    class Meta: 
        model = Task
        fields = ['task']

def index(request):
    tasks = Task.objects.all()
    return render(request, "task/index.html", {
        "tasks": tasks
    })
# Add a new task:
def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(request, "task/add.html", {
                "form": form
            })
        

    return render(request, "task/add.html", {
        "form": NewTaskForm()
    })

def complete_task(request, task_id): 
    task = get_object_or_404(Task, id=task_id)
    task.completed = not task.completed
    task.save()
    return HttpResponseRedirect(reverse("task:index"))

def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return HttpResponseRedirect(reverse("task:index"))

def edit_task(request, task_id):
    task = get_object_or_404(Task,id=task_id)
    if request.method == "POST":
        form = NewTaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("task:index"))
    else:
        form = NewTaskForm(instance=task)
    return render(request, "task/edit.html", {
        "form": form, 
        "task_id": task_id
    })
        

task/templates/task/add.html
{% extends "task/layout.html" %}

{% block body %}
        <h1>Add Task:</h1>
        <form action="{% url 'task:add' %}" method="post">
            {% csrf_token %}
            <!-- <input type="text" name="task"> -->
             {{ form.as_p }}
            <button type="submit">Add Task</button>
       </form>
       <a href="{% url 'task:index' %}">VIEW TASKS</a>
{% endblock %}

task/templates/task/edit.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>EDIT TASK</h1>
    <form action ="{% url 'task:edit_task' task_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    <a href="{% url 'task:index' %}">Back to Tasks</a>
{% endblock %}

task/templates/task/index.html
{% extends "task/layout.html" %}
{% block body %}
    <h1>TASKS: </h1>
       <ul>
            {% for task in tasks %}
                <li>
                    <a href="{% url 'task:complete_task' task.id %}">
                        {% if task.completed %}
                            <strike>{{ task.task }}</strike>
                        {% else %}
                            {{ task.task }}
                        {% endif %}
                    </a>
                    <span>
                        <a href="{% url 'task:edit_task' task.id %}">EDIT</a>
                        <a href="{% url 'task:delete_task' task.id %}">DELETE</a>
                    </span>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'task:add' %}">Add a New Task</a>
{% endblock %}
 

task/templates/task/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Task App{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'task/styles.css' %}">
    </head>
    <body>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>